### ISSUE TITLE
when building with ionic/cordova, receive error "Cannot find module '../../constants'"

### ISSUE THREAD

**Issue by basisesports** [ComethruApp/app#197]
I'm trying to build the app to try it out because I'm not a Yale student. When I go to build, it's giving me exit code 1:

Cannot find module '../../constants'.

import * as Constants from '../../constants';

Any help would be appreciated. What I've been able to see looks super interesting! Would love to be able to toy around with it.

**Comment by ErikBoesen** [comment]
This file is ignored for security. You will need to create a file at that location and declare the appropriate variables. You can find out what variables you need by searching around the code for `Constants.`
